
IF NOT EXISTS (
    SELECT * FROM sys.tables WHERE name = 'PROJECTS' AND type = 'U'
)
CREATE TABLE [PROJECTS] (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PROJECTGUID UNIQUEIDENTIFIER UNIQUE DEFAULT NEWID(),
    [COUNTRY] NVARCHAR(50),
    [YEAR] INT,
    [ACTION_TITLE] NVARCHAR(200),
    [ANNUAL_ACTION_TITLE] NVARCHAR(100),
    [FILENAME] NVARCHAR(100),
    [COLUMN_1_3_1_TOTAL_AMOUNT] INT,
    [GLOBAL_INDIRECT_MANAGEMENT_AMOUNT] NVARCHAR(50),
	[P1] INT,
    [P2] INT,
    [P3] INT,
    [Support_Measures] INT,
    [SO_Classification] NVARCHAR(max),
    CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CREATED_BY NVARCHAR(100) NOT NULL DEFAULT 'Initial upload',
    UPDATED_DATE DATETIME,
    UPDATED_BY NVARCHAR(100)
);

INSERT INTO [PROJECTS] (
    [COUNTRY], 
    [YEAR], 
    [ACTION_TITLE], 
    [ANNUAL_ACTION_TITLE], 
    [FILENAME], 
    [COLUMN_1_3_1_TOTAL_AMOUNT], 
    [GLOBAL_INDIRECT_MANAGEMENT_AMOUNT], 
    [P1], 
    [P2], 
    [P3], 
    [Support_Measures],[SO_Classification]
)  VALUES (N'Belize',2023,N'Effective and sustainable management of southern and western part of Belize',N'Annual action plan 2023 for Belize',N'C_2023_8229_F1_ANNEX_EN_V3_P1_3116610_p3.txt',12600000,N'9 500 000',10458000,0,0,0,N'1. Green growth and sustainable socio-economic development => a) Socio-economic development of the southern districts of Belize fostered by promoting a green model of development.
1. Green growth and sustainable socio-economic development => b) Good governance practices and territorial approach strengthened at the village and district levels.'),
	(N'Belize',2021,N'European Union- Belize Cooperation Facility for identification and implementation of actions under the MIP 2021-2027',N'Support measures 2021 for Belize',N'C_2021_9375_F1_ANNEX_EN_V2_P1_1629790_p3.txt',1000000,N'400 000',0,0,0,1000000,N'[No priority area => no link with MIP]'),
	(N'Bhutan',2021,N'Promoting Inclusive, Sustainable, and Resilient Agri-Food Systems in Bhutan',N'Annual action plan 2021 for Bhutan',N'C_2021_9284_F1_ANNEX_EN_V1_P1_1674789_p3.txt',15000000,N'1 400 000',6000000,0,0,0,N'1. Climate Change, green growth for resilient Bhutan => b) Scale-up climate resilient approaches for sustainable management and conservation of natural resources
1. Climate Change, green growth for resilient Bhutan => c) Enhance food and nutrition security
1. Climate Change, green growth for resilient Bhutan => d) Promote inclusive and effective RNR service delivery'),
	(N'Bhutan',2022,N'Supporting Good Governance and Digitalisation in Bhutan',N'Annual action plan 2022 for Bhutan',N'C_2022_7944_F1_ANNEX_EN_V1_P1_2307869_p3.txt',9300000,NULL,0,8277000,1023000,0,N'2. Good Governance for inclusive socio-economic development => a) Strengthen Good Governance through reforms in Local Governments (LG) and public service delivery.
2. Good Governance for inclusive socio-economic development => c) Enhance monitoring and oversight mechanisms.
3. Digital Transition: a driver for change in education and public services delivery => a) Strengthen digitalisation in Education nationwide.
3. Digital Transition: a driver for change in education and public services delivery => b) Strengthen digitalisation of public services to enhance efficiency, efficacy, transparency and accountability.'),
	(N'Botswana',2022,N'Accelerating Sustainable and Productive Investment in Renewable Energy & Efficiency (ASPIRE)',N'Annual action plan 2022 for Botswana',N'C_2022_9316_F1_ANNEX_EN_V2_P1_2287150_p3.txt',5500000,N'0',4400000,1100000,0,0,N'1. Green Transformation => a) Promote and increase access to affordable, reliable and sustainable energy through the expansion of renewable energy generation
2. Economic Diversification and Jobs => a) Support the economic diversification drive of Botswana, by facilitating investment and trade opportunities'),
	(N'Botswana',2022,N'EU support to Digital Transformation in Botswana',N'Annual action plan 2022 for Botswana',N'C_2022_9316_F1_ANNEX_EN_V2_P1_2287151_p3.txt',5000000,N'4 700 000',0,5000000,0,0,N'2. Economic Diversification and Jobs => a) Support the economic diversification drive of Botswana, by facilitating investment and trade opportunities
2. Economic Diversification and Jobs => b) Contribute to Botswana’s digital transformation
2. Economic Diversification and Jobs => c) Improve the quality and labour-market relevance of the TVET system in order to enhance skills availability and increased employability in the green and digital sectors'),
	(N'Botswana',2022,N'Botswana-EU Support Measures Facility',N'Annual action plan 2022 for Botswana',N'C_2022_9316_F1_ANNEX_EN_V2_P1_2287152_p3.txt',2500000,N'0',0,0,0,2500000,N'[No priority area => no link with MIP]'),
	(N'Republic of the Congo',2021,N'Congo Digital - Projet de blending pour la transformation numérique',N'Annual action plan 2021 for the Republic of Congo (French)',N'C_2021_9297_F1_ANNEX_FR_V1_P1_1642310_p3.txt',15000000,N'0',5250000,0,0,0,N'1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => a) Contribuer au développement d''une économie diversifiée et renforcer les capacités du secteur privé, notamment des très petites, petites et moyennes entreprises, en mettant l''accent sur l''agriculture, des modes de production durables et circulaires, des conditions de travail dignes, l''entrepreneuriat et la formation professionnelle qualifiante.
1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => b) Contribuer au développement d''un climat d''affaires favorable, une meilleure gouvernance économique et gestion des finances publiques.
1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => c) Favoriser le (e-)commerce, les investissements verts, faciliter l''accès au financement des entreprises, et renforcer la compétitivité de l''économie congolaise.'),
	(N'Republic of the Congo',2021,N'Programme d''appui à la professionnalisation de la police congolaise et à la mise en place de commissariats pilotes',N'Annual action plan 2021 for the Republic of Congo (French)',N'C_2021_9297_F1_ANNEX_FR_V1_P1_1642329_p3.txt',5000000,N'4 800 000',0,0,5000000,0,N'3. Démocratie, droits de l''Homme et gouvernance participative => a) Renforcer la protection des droits de populations vulnérables'),
	(N'Republic of the Congo',2021,N'Mesures d''appui',N'Annual action plan 2021 for the Republic of Congo (French)',N'C_2021_9297_F1_ANNEX_FR_V1_P1_1642349_p3.txt',5000000,N'0',0,0,0,0,N'[No priority area => no link with MIP]'),
	(N'Republic of the Congo',2021,N'Contribution à l''opérationnalisation du programme d''utilisation durable des terres, dans le cadre de l''initiative pour la forêt d''Afrique centrale (CAFI)',N'Annual action plan 2021 for the Republic of Congo (French)',N'C_2021_9297_F1_ANNEX_FR_V1_P1_1642369_p3.txt',15000000,N'15 000 000',0,13500000,1500000,0,N'1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => a) Contribuer au développement d''une économie diversifiée et renforcer les capacités du secteur privé, notamment des très petites, petites et moyennes entreprises, en mettant l''accent sur l''agriculture, des modes de production durables et circulaires, des conditions de travail dignes, l''entrepreneuriat et la formation professionnelle qualifiante.
2. Gestion durable des ressources naturelles, préservation de l''environnement et lutte contre le changement climatique => a) Contribuer à la gestion durable des ressources naturelles et la préservation de la biodiversité, notamment du couvert forestier, par l''utilisation durable des terres et l''amélioration de la gouvernance forestière, la promotion d''une économie forestière et d''une agriculture durables.
3. Démocratie, droits de l''Homme et gouvernance participative => b) Renforcer la participation active de la société civile au suivi des politiques, au développement socio-économique du pays et à la gestion durable des ressources naturelles.'),
	(N'Republic of the Congo',2022,N'Programme de promotion des énergies renouvelables et de l''électrification rurale en République du Congo',N'Annual action plan 2022 for the Republic of Congo (French)',N'C_2022_8756_F1_ANNEX_FR_V1_P1_2313230_p3.txt',5000000,N'0',0,0,0,0,NULL),
	(N'Republic of the Congo',2023,N'Programme d''appui à la transition économique verte et à l''amélioration du climat des affaires en République du Congo',N'Annual action plan 2023 for the Republic of Congo (French)',N'C_2023_2964_F1_ANNEX_FR_V1_P1_2675830_p3.txt',16000000,N'3 000 000',11200000,4800000,0,0,N'1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => a) Contribuer au développement d''une économie diversifiée et renforcer les capacités du secteur privé, notamment des très petites, petites et moyennes entreprises, en mettant l''accent sur l''agriculture, des modes de production durables et circulaires, des conditions de travail dignes, l''entrepreneuriat et la formation professionnelle qualifiante.
1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => b) Contribuer au développement d''un climat d''affaires favorable, une meilleure gouvernance économique et gestion des finances publiques.
1. Gouvernance économique et transition vers une économie verte, diversifiée et digitalisée => c) Favoriser le (e-)commerce, les investissements verts, faciliter l''accès au financement des entreprises, et renforcer la compétitivité de l''économie congolaise.
2. Gestion durable des ressources naturelles, préservation de l''environnement et lutte contre le changement climatique => a) Contribuer à la gestion durable des ressources naturelles et la préservation de la biodiversité, notamment du couvert forestier, par l''utilisation durable des terres et l''amélioration de la gouvernance forestière, la promotion d''une économie forestière et d''une agriculture durables.'),
	(N'Republic of the Congo',2023,N'‘ Programme d’appui à la société civile au Congo et à sa contribution à l’égalité de genre pour un développement socio-économique inclusif ’',N'Annual action plan 2023 for the Republic of Congo (French)',N'C_2023_2964_F1_ANNEX_FR_V1_P1_2675831_p3.txt',5000000,N'0',0,0,3500000,0,N'3. Démocratie, droits de l''Homme et gouvernance participative => a) Renforcer la protection des droits de populations vulnérables
3. Démocratie, droits de l''Homme et gouvernance participative => b) Renforcer la participation active de la société civile au suivi des politiques, au développement socio-économique du pays et à la gestion durable des ressources naturelles.'),
	(N'Dominican Republic',2022,N'Transition to a greener and more inclusive economy',N'Annual action plan 2022 for Dominican Republic',N'C_2022_9779_F1_ANNEX_EN_V3_P1_2360310_p3.txt',13000000,NULL,7800000,0,5200000,0,N'1. Increasing economic opportunities, especially for women and youth => a) Improving the Business Climate, and enhancing trade and investments with the EU.
1. Increasing economic opportunities, especially for women and youth => b) Facilitate MSMEs development generating a prompt post-COVID recovery, through improving productivity, strengthening value chains and competitiveness, with special focus on efficiency and clean resources cycles, linked to circular economy and digital solutions, and enhancing the participation of women and youth.
3. A modern state close to its citizens => a) Closing the circle on public finance management reform.
3. A modern state close to its citizens => b) Empower autonomous and accountable LAs to manage, finance and implement local development'),
	(N'Dominican Republic',2023,N'Support Measures for Dominican Republic',N'Support measures 2023 for the Dominican Republic',N'C_2023_8800_F1_ANNEX_EN_V1_P1_3146310_p3.txt',2000000,N'910 000',0,0,0,2000000,N'[No priority area => no link with MIP]'),
	(N'Ecuador',2023,N'‘A Green Deal for Ecuador. An inclusive, sustainable, and resilient economy, stimulated by innovations and investments at decentralised level’',N'Annual action plan 2023 for Ecuador - part 1',N'C_2023_3234_F1_ANNEX_EN_V2_P1_2692090_p3.txt',15000000,N'11 000 000',0,0,15000000,0,N'2. Enhance climate and environment action on green innovation and productivity => b) Increase the implementation of green innovation and circular economy practices with the private sector, local authorities and higher education system.
2. Enhance climate and environment action on green innovation and productivity => c) Improve long-Term Strategies and Climate Adaptation Plans through local authorities.
3. Good governance => b) Decentralise public management and decision-making processes'),
	(N'Ecuador',2023,N'“Strengthening of inclusive Ecuadorian democratic governance and prevention of violence against women”',N'Annual action plan 2023 for Ecuador - part 1',N'C_2023_3234_F1_ANNEX_EN_V2_P1_2692091_p3.txt',2800000,N'1 800 000',0,0,2800000,0,N'3. Good governance => d) Increase the equal participation of women, men, girls and boys, in all their diversity, in decision-making processes, in all spheres and at all levels of political and public life, including online, taking on leadership roles, to enjoy and exercise their human rights and seek redress if these rights are denied.'),
	(N'Ecuador',2024,N'‘Ukumari EU - Ecuador Forest Partnership: Traditional knowledge for forest conservation and bio-economy promotion’',N'Annual action plan 2024 for Ecuador',N'C_2023_8516_F1_ANNEX_EN_V3_P1_3109150_p3.txt',5000000,N'5 000 000',0,5000000,0,0,N'2. Enhance climate and environment action on green innovation and productivity => a) Increase implementation of circular economy and bio-economy policies with the participation of main public and private actors with a social and gender balanced approach.
2. Enhance climate and environment action on green innovation and productivity => b) Increase the implementation of green innovation and circular economy practices with the private sector, local authorities and higher education system.'),
	(N'Ecuador',2024,N'‘Spearheading Digital Governance transformation in Ecuador’',N'Annual action plan 2024 for Ecuador',N'C_2023_8516_F1_ANNEX_EN_V3_P1_3109151_p3.txt',5200000,N'0',0,0,0,0,N'3. Good governance => a) Increase the efficiency, effectiveness and transparency of public administration
3. Good governance => b) Decentralise public management and decision-making processes
3. Good governance => c) Enhance independent work of oversight bodies to undertake effective technical evaluations or inspections of the executive and conduct performance monitoring available to the public.
3. Good governance => d) Increase the equal participation of women, men, girls and boys, in all their diversity, in decision-making processes, in all spheres and at all levels of political and public life, including online, taking on leadership roles, to enjoy and exercise their human rights and seek redress if these rights are denied.'),
	(N'Honduras',2021,N'Towards a Decarbonised Economy: Adapting Agricultural Production to Climate Change in the context of the EU-Honduras Voluntary Partnership Agreement',N'Annual action plan 2021 for Honduras',N'C_2021_9377_F1_ANNEX_EN_V3_P1_1652130_p3.txt',7450000,N'1 300 000',3725000,0,3725000,0,N'1. Sustainable Management of Natural Resources and Climate Change => a) Land Use, Land-Use Change and Forestry (LULUCF) emissions reduced and carbon absorbed compared to Business as Usual (BAU).
3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.'),
	(N'Honduras',2021,N'“Cooperation Facility for Honduras”',N'Annual action plan 2021 for Honduras',N'C_2021_9377_F1_ANNEX_EN_V3_P1_1652131_p3.txt',11000000,N'0',0,0,11000000,0,N'3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.
3. Rule of Law and Democratic Governance => b) Contribute to strengthening of the democratic system and increasing citizen participation with a specific focus on vulnerable groups, especially women.'),
	(N'Honduras',2023,N'VPA & Beyond: Voluntary Partnership Agreement, Forest Partnership and Green Business',N'Annual action plan 2023 for Honduras',N'C_2023_5548_F1_ANNEX_EN_V3_P1_2814170_p3.txt',23400000,N'16 000 000',0,0,0,0,N'1. Sustainable Management of Natural Resources and Climate Change => a) Land Use, Land-Use Change and Forestry (LULUCF) emissions reduced and carbon absorbed compared to Business as Usual (BAU).
2. Employment, Decent Work and Growth => b) Foster an enabling environment for the creation and development of micro and small enterprises through innovative credit access facilities and information technologies.
3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.'),
	(N'Honduras',2024,N'Climate and Energy: Resilient infrastructures adapted to climate change and access to clean energy',N'Annual action plan 2024 for Honduras',N'C_2024_8508_F1_ANNEX_EN_V2_P1_3776634_p3.txt',23500000,N'0',23500000,0,0,0,N'1. Sustainable Management of Natural Resources and Climate Change => a) Land Use, Land-Use Change and Forestry (LULUCF) emissions reduced and carbon absorbed compared to Business as Usual (BAU).'),
	(N'Honduras',2024,N'Access to Sustainable Finance for Green and Climate-Smart Value Chains',N'Annual action plan 2024 for Honduras',N'C_2024_8508_F1_ANNEX_EN_V2_P1_3776635_p3.txt',7350000,N'0',0,0,0,0,N'1. Sustainable Management of Natural Resources and Climate Change => a) Land Use, Land-Use Change and Forestry (LULUCF) emissions reduced and carbon absorbed compared to Business as Usual (BAU).
2. Employment, Decent Work and Growth => b) Foster an enabling environment for the creation and development of micro and small enterprises through innovative credit access facilities and information technologies.'),
	(N'Honduras',2024,N'Support Transparency Efforts and the Fight against Corruption',N'Annual action plan 2024 for Honduras',N'C_2024_8508_F1_ANNEX_EN_V2_P1_3776636_p3.txt',7500000,N'0',0,0,0,0,N'3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.
3. Rule of Law and Democratic Governance => b) Contribute to strengthening of the democratic system and increasing citizen participation with a specific focus on vulnerable groups, especially women.'),
	(N'Honduras',2023,N'Support to the electoral cycle for transparent and peaceful elections in Honduras',N'Multiannual action plan 2023 (part 2) and 2024 (part 1) for Honduras',N'C_2023_8429_F1_ANNEX_EN_V2_P1_3120910_p3.txt',10000000,N'0',0,0,10000000,0,N'3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.
3. Rule of Law and Democratic Governance => b) Contribute to strengthening of the democratic system and increasing citizen participation with a specific focus on vulnerable groups, especially women.'),
	(N'Honduras',2023,N'Building a citizen-oriented, equally accessible, effective, independent and accountable justice system in Honduras',N'Multiannual action plan 2023 (part 2) and 2024 (part 1) for Honduras',N'C_2023_8429_F1_ANNEX_EN_V2_P1_3120911_p3.txt',8000000,N'0',0,0,8000000,0,N'3. Rule of Law and Democratic Governance => a) Support national efforts and provide institutional strengthening to guarantee the universal application of the law and protection of human rights, particularly focusing on transparency and the fight against corruption.
3. Rule of Law and Democratic Governance => b) Contribute to strengthening of the democratic system and increasing citizen participation with a specific focus on vulnerable groups, especially women.'),
	(N'Indonesia',2021,N'EU-Indonesia Cooperation Facility',N'Annual action plan 2021 for Indonesia',N'C_2021_9307_F1_ANNEX_EN_V2_P1_1662569_p3.txt',NULL,N'0',0,0,0,0,N'1. Trade and Connectivity => c) Promote regulatory cooperation, including on standards and other regulatory measures of relevance for market access, as well as on other relevant policies in the trade, digital and economic diplomacy area.
2. Governance and Security => a) Policy Dialogues under the PCA, including political affairs, trade and investment, security, (including, e.g., trafficking in human beings, cybercrime, drugs trafficking, organised crime, terrorism), human rights, child labour, decent work, gender equality and women''s empowerment, LGBTIQ, environment/climate change/energy, disaster risk management, (higher) education, digital issues, and development.
2. Governance and Security => c) Structured dialogue with civil society organisations, youth organisations, LGBTIQ organisations and women''s organisations to ensure the mainstreaming of cross-cutting issues.
3. Green Deal => e) Dialogue and cooperation on other areas of the Green Deal and accompanying measures to external aspects of EU policies in this field, such as National Determined Contributions (NDCs), emission trading, carbon pricing and Carbon Border Adjustment Mechanism, taxonomy, "just transition”, FLEGT and forest partnerships, opportunities of the Green Deal access to jobs, women and girls as agents of change etc.'),
	(N'Iraq',2021,N'Support to durable solutions for Iraq’s displaced populations: integration into the national labour market and national systems for education and social protection',N'Annual action plan 2021 for Iraq',N'C_2021_9369_F1_ANNEX_EN_V1_P1_1587790_p3.txt',75000000,N'54 200 000',0,0,0,0,NULL),
	(N'Iraq',2023,N'Greening Iraq',N'Annual action plan 2023 for Iraq',N'C_2023_8490_F1_ANNEX_EN_V2_P1_3049010_p3.txt',18900000,N'18 900 000',0,0,0,0,NULL),
	(N'Iraq',2023,N'Promoting Girls’ Education in Iraq',N'Annual action plan 2023 for Iraq',N'C_2023_8490_F1_ANNEX_EN_V2_P1_3049011_p3.txt',1000000,N'0',0,0,0,0,NULL),
	(N'Jamaica',2022,N'The Digital Transitioning Programme for Jamaica (Digital Jamaica)',N'Annual action plan 2022 for Jamaica',N'C_2022_9317_F1_ANNEX_EN_V4_P1_2316630_p3.txt',9500000,N'0',9500000,0,0,0,N'1. Sustainable and inclusive economy (focusing on digital transitioning) => a) to increase access to gender-responsive, accountable and effective digital skills and literacy products and services, especially for the vulnerable.
1. Sustainable and inclusive economy (focusing on digital transitioning) => b) to increase use of robust, affordable and secure broadband infrastructure for end users, businesses and the government, including last mile technology for poor remote communities.
1. Sustainable and inclusive economy (focusing on digital transitioning) => c) to promote the digital transformation of existing MSMEs and the growth of the technology sector.'),
	(N'Jamaica',2024,N'Support to the Sustainable Urban Development of Kingston',N'Annual action plan 2024 for Jamaica',N'C_2024_7927_F1_ANNEX_EN_V2_P1_3684475_p3.txt',7200000,N'900 000',0,6480000,720000,0,N'2. Climate change and environment => a) to improve resilience to impacts of climate change and disasters caused by natural events affecting sustained economic and social development.
2. Climate change and environment => b) to enhance sustainable management of natural resources.
3. Good governance and human security => a) Jamaica society is safer, more inclusive and resilient with emphasis on a rights-based approach'),
	(N'Jamaica',2024,N'Inclusive Safety: Supporting Jamaica’s Strategy for Citizen Security, School Safety and Gender Based Violence Reduction',N'Annual action plan 2024 for Jamaica',N'C_2024_7927_F1_ANNEX_EN_V4_P1_3684476_p3.txt',8800000,N'0',0,0,8800000,0,N'3. Good governance and human security => a) Jamaica society is safer, more inclusive and resilient with emphasis on a rights-based approach
3. Good governance and human security => b) To improve protection of women, men, girls and boys from all forms of gender-based violence in the public and private spheres, in the workplace and online.'),
	(N'Jamaica',2021,N'European Union - Jamaica Cooperation Facility',N'Support measures 2021 for Jamaica',N'C_2021_9371_F1_ANNEX_EN_V1_P1_1629290_p3.txt',1500000,N'580 000',0,0,0,1500000,N'[No priority area => no link with MIP]'),
	(N'Kazakhstan',2022,N'EU-Kazakhstan Cooperation Facility 2022-2023',N'Multiannual action plan 2022-2023 for Kazakhstan',N'C_2021_9454_F1_ANNEX_EN_V1_P1_1584990_p3.txt',9000000,N'950 000',0,0,0,0,N'[No priority area => no link with MIP]'),
	(N'Kazakhstan',2024,N'EU-Kazakhstan Cooperation Facility 2024-2027',N'Multiannual action plan 2024-2027 for Kazakhstan',N'C_2024_9253_F1_ANNEX_EN_V3_P1_3718875_p3.txt',11000000,N'4 000 000',0,0,0,0,N'[No priority area => no link with MIP]'),
	(N'Malaysia',2024,N'EU-Malaysia Cooperation Facility',N'Addendum 2024 to the multiannual action plan 2021-2023 for Malaysia',N'C_2024_5860_F1_ANNEX_EN_V2_P1_3616535_p3.txt',12000000,N'3 100 000',12000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU interests and political priorities in Malaysia, focusing on connectivity, human development, and the Green Deal, while tackling areas of common interest.
1. Cooperation Facility => b) Support policy dialogues on connectivity, trade, SDG commitments, and engage with civil society, youth, women''s organisations, and public diplomacy.
1. Cooperation Facility => c) Reinforce EU strategic interests and priorities in Malaysia through various tools, initiatives, and activities.
1. Cooperation Facility => d) Enhance the EU-Malaysia partnership, strengthen synergies on mutual interests and values, and increase understanding and visibility of the EU''s role.'),
	(N'Malaysia',2021,N'EU-Malaysia Cooperation Facility',N'Multiannual action plan 2021-2023 for Malaysia',N'C_2021_9278_F1_ANNEX_EN_V3_P1_1662409_p3.txt',12000000,N'1 000 000',12000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU interests and political priorities in Malaysia, focusing on connectivity, human development, and the Green Deal, while tackling areas of common interest.
1. Cooperation Facility => b) Support policy dialogues on connectivity, trade, SDG commitments, and engage with civil society, youth, women''s organisations, and public diplomacy.
1. Cooperation Facility => c) Reinforce EU strategic interests and priorities in Malaysia through various tools, initiatives, and activities.
1. Cooperation Facility => d) Enhance the EU-Malaysia partnership, strengthen synergies on mutual interests and values, and increase understanding and visibility of the EU''s role.'),
	(N'Malaysia',2025,N'EU-Malaysia Cooperation Facility II',N'Multiannual action plan 2025-2027 for Malaysia',N'C_2024_8839_F1_ANNEX_EN_V2_P1_3818569_p3.txt',8000000,N'2 700 000',8000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU interests and political priorities in Malaysia, focusing on connectivity, human development, and the Green Deal, while tackling areas of common interest.
1. Cooperation Facility => b) Support policy dialogues on connectivity, trade, SDG commitments, and engage with civil society, youth, women''s organisations, and public diplomacy.
1. Cooperation Facility => c) Reinforce EU strategic interests and priorities in Malaysia through various tools, initiatives, and activities.
1. Cooperation Facility => d) Enhance the EU-Malaysia partnership, strengthen synergies on mutual interests and values, and increase understanding and visibility of the EU''s role.'),
	(N'Paraguay',2022,N'Forest 4life Paraguay',N'Annual action plan 2022 for Paraguay',N'C_2022_7906_F1_ANNEX_EN_V3_P1_2275190_p3.txt',12000000,N'0',0,0,0,0,N'1. Green and Resilient Economy => a) To preserve and restore biodiversity by fighting against deforestation and promoting sustainable forest management.
1. Green and Resilient Economy => b) To support sustainable production models, including circular economy, and sustainable value chains development.'),
	(N'Paraguay',2023,N'Violence against women and girls in Paraguay: improving prevention and attention services',N'Annual action plan 2023 for Paraguay – Part 1',N'C_2023_5290_F1_ANNEX_EN_V4_P1_2816410_p3.txt',4000000,N'2 300 000',0,4000000,0,0,N'2. Fighting against Inequalities => c) To enhance gender equality and reduce gender-based violence.'),
	(N'Paraguay',2024,N'Support for the promotion and strengthening of the sustainability and competitiveness of Paraguay’s agricultural, forestry and agro-industrial value chains',N'Individual measure 2024 for Paraguay',N'C_2024_5528_F1_ANNEX_EN_V3_P1_3568075_p3.txt',10000000,N'7 000 000',10000000,0,0,0,N'1. Green and Resilient Economy => a) To preserve and restore biodiversity by fighting against deforestation and promoting sustainable forest management.
1. Green and Resilient Economy => b) To support sustainable production models, including circular economy, and sustainable value chains development.'),
	(N'Paraguay',2024,N'Boosting opportunities through education: EDU-Impulsa Paraguay',N'Multiannual action plan 2024-2025 for Paraguay',N'C_2024_7935_F1_ANNEX_EN_V2_P1_3724775_p3.txt',12000000,N'9 000 000',0,12000000,0,0,N'2. Fighting against Inequalities => a) To promote the inclusiveness of the education system through improved access and reduction of exclusion of the most vulnerable children and adolescents from school.
2. Fighting against Inequalities => b) To promote labour integration, employability and formalisation through the implementation of Social Protection programmes.'),
	(N'Paraguay',2024,N'“Promote access to formal employment for young people (18-29 years old) in a vulnerable situation.”',N'Multiannual action plan 2024-2025 for Paraguay',N'C_2024_7935_F1_ANNEX_EN_V2_P1_3724776_p3.txt',10000000,N'6 000 000',0,10000000,0,0,N'2. Fighting against Inequalities => b) To promote labour integration, employability and formalisation through the implementation of Social Protection programmes.'),
	(N'Paraguay',2024,N'Support Measures for Paraguay',N'Multiannual action plan 2024-2025 for Paraguay',N'C_2024_7935_F1_ANNEX_EN_V2_P1_3724777_p3.txt',1000000,N'0',0,0,0,1000000,N'[No priority area => no link with MIP]'),
	(N'Thailand',2024,N'EU-Thailand Cooperation Facility',N'Addendum 2024 to the multiannual action plan 2021-2023 for Thailand',N'C_2024_5861_F1_ANNEX_EN_V2_P1_3616915_p3.txt',12000000,N'5 400 000',12000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU-Thailand partnership through policy dialogues on shared interests including security, human rights, good governance, rule of law, climate, energy, and digital transition.
1. Cooperation Facility => b) Promote sustainable development and economic cooperation, including trade, regulatory convergence, responsible value chains, and business partnerships.
1. Cooperation Facility => c) Support the implementation of the 2030 Agenda, SDGs, and Gender Action Plan, engaging civil society, youth, and women''s organizations.
1. Cooperation Facility => d) Advance the external dimension of the European Green Deal, focusing on climate action, energy transition, circular economy, and environmental protection.
1. Cooperation Facility => e) Enhance public diplomacy and strategic communication to increase understanding and visibility of the EU''s role and values.'),
	(N'Thailand',2021,N'EU-Thailand Cooperation Facility',N'Multiannual action plan 2021-2023 for Thailand',N'C_2021_9286_F1_ANNEX_EN_V2_P1_1662269_p3.txt',12000000,N'1 000 000',12000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU-Thailand partnership through policy dialogues on shared interests including security, human rights, good governance, rule of law, climate, energy, and digital transition.
1. Cooperation Facility => b) Promote sustainable development and economic cooperation, including trade, regulatory convergence, responsible value chains, and business partnerships.
1. Cooperation Facility => c) Support the implementation of the 2030 Agenda, SDGs, and Gender Action Plan, engaging civil society, youth, and women''s organizations.
1. Cooperation Facility => d) Advance the external dimension of the European Green Deal, focusing on climate action, energy transition, circular economy, and environmental protection.
1. Cooperation Facility => e) Enhance public diplomacy and strategic communication to increase understanding and visibility of the EU''s role and values.'),
	(N'Thailand',2025,N'EU-Thailand Cooperation Facility II',N'Multiannual action plan 2025-2027 for Thailand',N'C_2024_8840_F1_ANNEX_EN_V2_P1_3818589_p3.txt',8000000,N'2 700 000',8000000,0,0,0,N'1. Cooperation Facility => a) Strengthen EU-Thailand partnership through policy dialogues on shared interests including security, human rights, good governance, rule of law, climate, energy, and digital transition.
1. Cooperation Facility => b) Promote sustainable development and economic cooperation, including trade, regulatory convergence, responsible value chains, and business partnerships.
1. Cooperation Facility => c) Support the implementation of the 2030 Agenda, SDGs, and Gender Action Plan, engaging civil society, youth, and women''s organizations.
1. Cooperation Facility => d) Advance the external dimension of the European Green Deal, focusing on climate action, energy transition, circular economy, and environmental protection.
1. Cooperation Facility => e) Enhance public diplomacy and strategic communication to increase understanding and visibility of the EU''s role and values.'),
	(N'Turkmenistan',2022,N'Turkmenistan Cooperation Facility 2022-2023',N'Multiannual action plan 2022-2023 for Turkmenistan',N'C_2021_9285_F1_ANNEX_EN_V1_P1_1584970_p3.txt',11000000,N'0',5500000,5500000,0,0,N'1. Green aspects of the economy => a) Support the creation of a greener, more sustainable, more inclusive and more investment-friendly business environment.
1. Green aspects of the economy => f) Promote more frequent use of modern, green technologies that address the effects of climate change.
2. Improving the business climate (with a focus on agriculture/rural development and support to trade development) => a) Improve the investment climate, including a reduction of corruption and fair and transparent competition.
2. Improving the business climate (with a focus on agriculture/rural development and support to trade development) => d) Assist in preparation for WTO accession, including trade facilitation, elimination of physical and non-physical barriers to trade, improvement of border management, e-commerce, and alignment with international regulatory practices and standards.'),
	(N'Turkmenistan',2024,N'EU - Turkmenistan Cooperation Facility 2024-2027',N'Multiannual action plan 2024-2027 for Turkmenistan',N'C_2024_9201_F1_ANNEX_EN_V4_P1_3719355_p3.txt',7000000,NULL,0,0,0,0,N'[No priority area => no link with MIP]');

	select  [COUNTRY], 
    [YEAR], 
    [ACTION_TITLE], 
    [ANNUAL_ACTION_TITLE], 
    [FILENAME], 
    [COLUMN_1_3_1_TOTAL_AMOUNT], 
    [GLOBAL_INDIRECT_MANAGEMENT_AMOUNT], 
   [P1] ,
    [P2] ,
    [P3] ,
    [Support_Measures] from projects