
CREATE PROCEDURE GET_CHART2_TOP_CAD_DATA
AS
BEGIN
SELECT DISTINCT
    c.NAME Name,
    c.CODE_CAD CadCode,
    p.YEAR Year,
    p.COUNTRY Country,
    CASE 
        WHEN p.YEAR BETWEEN 2021 AND 2024 THEN '2021-2024'
        WHEN p.YEAR BETWEEN 2025 AND 2027 THEN '2025-2027'
        WHEN p.YEAR BETWEEN 2021 AND 2027 THEN '2021-2027'
        ELSE 'Other Period'
    END AS YearRange
FROM 
    PROJECTS p
INNER JOIN 
    CAD c ON p.FILENAME = c.FILENAME
ORDER BY 
    p.COUNTRY, p.YEAR, c.NAME;

END